// GENERATED by tools/render_44.py --emit-js — DO NOT EDIT.
// Source of truth is render_manifest.json.
const RENDER_MANIFEST = {
  "frozen": true,
  "renderVersion": 1,
  "cameraPitch": 44,
  "cameraDistance": 5200,
  "projectionScale": 1.0,
  "yawAngles": [
    0,
    45,
    90,
    135,
    180,
    225,
    270,
    315
  ],
  "lightRig": {
    "key": {
      "azimuth": 315,
      "elevation": 52,
      "intensity": 1.0,
      "colour": "#fff4e0"
    },
    "fill": {
      "azimuth": 135,
      "elevation": 28,
      "intensity": 0.35,
      "colour": "#9fc4ff"
    },
    "rim": {
      "azimuth": 180,
      "elevation": 62,
      "intensity": 0.55,
      "colour": "#ffffff"
    },
    "ambient": {
      "intensity": 0.22,
      "colour": "#4a5a78"
    },
    "shadow": {
      "enabled": true,
      "opacity": 0.45,
      "softness": 0.25
    }
  },
  "modelScaleUnit": "1 unit = 1 game pixel at projectionScale 1.0",
  "pivotConvention": "origin at the FLOOR CONTACT POINT, centred on the footprint",
  "groundContactRule": "lowest geometry touches z=0; nothing floats or sinks",
  "spriteBounds": {
    "maxWidth": 1024,
    "maxHeight": 1024
  },
  "trimRule": "trim fully transparent rows/columns, then re-pad symmetrically",
  "paddingPx": 8,
  "atlasRule": "one atlas per set, power-of-two, no rotation, 2px bleed",
  "namingConvention": "{set}_d{dir}",
  "heightLayers": {
    "floor": 0,
    "floorHazard": 1,
    "lowProp": 2,
    "looseParts": 3,
    "machineLower": 4,
    "body": 5,
    "tallProp": 6,
    "effects": 7,
    "ui": 8
  },
  "certification": {
    "passed": true,
    "date": "2026-08-20",
    "checkedBy": "Aaron",
    "checks": [
      "module occlusion is readable",
      "depth sorting is correct when a branch overhangs the Core",
      "every connector collar remains visible and targetable when a module is mounted in front of it",
      "silhouette stays legible against every Rust Yard floor",
      "eight-direction swaps are clean during a full rotation while firing",
      "damaged/RIP connector states are distinguishable at phone size",
      "no sprite bound clipping at maximum extent"
    ],
    "note": "Judged on the build after the Core was corrected to draw at model size. The first look failed check 1 \u2014 modules read as oversized \u2014 which was the Core drawing at two thirds scale beneath them, not the modules."
  }
};
